### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by gfleury** [gfleury/jenkins-tsuru-client-plugin#7]
[Bitbucket] Notifying commit build result
[Bitbucket] Build result notified
java.lang.NullPointerException
	at org.jenkinsci.plugins.tsuru.pipeline.TsuruAction$Execution.tsuruPerform(TsuruAction.java:203)
	at org.jenkinsci.plugins.tsuru.pipeline.TsuruAction$Execution.access$000(TsuruAction.java:85)
	at org.jenkinsci.plugins.tsuru.pipeline.TsuruAction$Execution$1.run(TsuruAction.java:132)
Finished: FAILURE

**Comment by gfleury** [comment]
Check if deployment list get failed.
